### ISSUE TITLE
Sensor showing as Unknown

### ISSUE THREAD

**Issue by jb123567** [unlobito/ha-hildebrandglow#25]
The intergration configured correctly, identifying that my account has a gas and electricity meter but the state remains "unknown". 

The logs shows the following error -

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
    state = self.state
  File "/config/custom_components/hildebrandglow/sensor.py", line 112, in state
    return self._state["data"][0][1]
IndexError: list index out of range

**Comment by unlobito** [comment]
Hi @jb123567, thanks for trying out the integration.

It seems the HTTP polling variant has been installed rather than the MQTT variant in pre-release #16. HTTP polling is hugely inefficient for Hildebrand, so I'd suggest trying https://github.com/unlobito/ha-hildebrandglow/releases/tag/0.1.0-beta instead. It's likely this also won't fully work (and requires MQTT to be enabled on your account).
