### ISSUE TITLE
Poll for readings (over REST) for non-DCC meters

### ISSUE THREAD

**Issue by plainmad** [unlobito/ha-hildebrandglow#26]
With the latest update switching to MQTT I have updated the integration and had MQTT enabled on my account. Now when I try it setting it up I get a message saying the integration failed to set up with the below error message in the log 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hildebrandglow/__init__.py", line 30, in async_setup_entry
    await hass.async_add_executor_job(glow.retrieve_cad_hardwareId)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hildebrandglow/glow.py", line 94, in retrieve_cad_hardwareId
    self.hardwareId = cad["hardwareId"]
KeyError: 'hardwareId'

**Comment by unlobito** [comment]
Hey @plainmad, thanks for writing in.

This seems like the integration failed to locate your Consumer Access Device among all the devices within your smart meter's Home Area Network. Are you using a [Glow stick Wifi CAD](https://www.hildebrand.co.uk/our-products/glow-stick-wifi-cad/) or another device?

**Comment by plainmad** [comment]
Thanks @unlobito 

The only CAD device is the standard one that was given to me when I went to smart meters. 

Whilst I appreciate this won’t be able to give me live time energy usage I was hoping it would still be able to give me the data I can get off the Glowmarket website/app which is still fairly up to date

**Comment by unlobito** [comment]
Merging #28 into this issue (thanks @BenWoodford!).

I think #12 would be the best place to tackle this, but I'm unsure how would be best to expose the sensors as configurable options since YAML configuration has fallen out of favour. Likewise, unsure how to best control for data being published as a sensor vs as a sensor attribute.

**Comment by si458** [comment]
Hi all,
i wondered if the was an update on this issue?
just signed up for the bright IOS app, added my british gas HUD and its showing all the data in the app no problem,
add the custom repo into my HA, then use my login details and i keep getting 
`2021-10-25 17:51:07 ERROR (MainThread) [custom_components.hildebrandglow] Couldn't find any CAD devices (e.g. Glow Stick)` im assuming thats because i have NO glow devices only the basic things (smart elec meter, smart gas meter and british gas HUD) ?

**Comment by HandyHat** [comment]
Hey @si458, I'm maintaining [a fork](https://github.com/HandyHat/ha-hildebrandglow-dcc) to pull data via the DCC which doesn't require glow hardware. As discussed [here](https://github.com/unlobito/ha-hildebrandglow/pull/36#issuecomment-915195357), once the MQTT version is stabler I'm going to look at merging it back with this repository.

**Comment by si458** [comment]
@HandyHat oh wow thank you! just removed this repo and added yours and it works a treat!
shows my gas/elec usage for today and the year! even now in the energy tab!
sadly my gas is showing no price but im having that argument at the moment with british gas as my smart monitor doesnt even show gas usage just that the gas has been disconnected haha 
while the bright app for ios is showing ALL my usage even down to the 30mins so fingers crossed!
