### ISSUE TITLE
Failed to Set up

### ISSUE THREAD

**Issue by bobbinz** [unlobito/ha-hildebrandglow#39]
Hiya,

I'm getting a failed to set up error in the integration.

Logs look like:
```
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hildebrandglow/glow.py:100
Integration: Hildebrand Glow (documentation)
First occurred: 9:15:09 (2 occurrences)
Last logged: 9:21:13

Error setting up entry for hildebrandglow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hildebrandglow/__init__.py", line 30, in async_setup_entry
    await hass.async_add_executor_job(glow.retrieve_cad_hardwareId)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hildebrandglow/glow.py", line 100, in retrieve_cad_hardwareId
    self.hardwareId = cad["hardwareId"]
KeyError: 'hardwareId'
`
```

I only have a linked SMETS2 meter and no hardware, is that the issue?

Adam

**Comment by bobbinz** [comment]
Used fork at https://github.com/HandyHat/ha-hildebrandglow-dc
